const mongoose=require('mongoose');
const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    location:{
        type:String,
        //required:true
    },
    age:{
        type:String,
        //required:true
    },
    phone:{
        type:String,
        //required:true
    },
    gender:{
        type:String,
       // required:true
    },
        //String=email
        appointPatient:[String], 
        rejectedAppoint:{type:mongoose.Schema.Types.Array},
        accepted:{type:mongoose.Schema.Types.Array},
        notifications:[String]
});
module.exports=mongoose.model('User',userSchema);
/*
,
    date:{
        type:Date,
        required:Date.now
    }
    */